name: any_link_web3
description: "JSON-RPC client, IPFS client, WalletConnect bridge, and decentralized gateway for any_link. Pure Dart."
version: 1.0.0
homepage: https://github.com/ramprasads090/any_link
repository: https://github.com/ramprasad090/any_link
issue_tracker: https://github.com/ramprasad090/any_link/issues

topics:
  - web3
  - blockchain
  - ethereum
  - ipfs
  - json-rpc

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  any_link:
    path: ../any_link

dev_dependencies:
  lints: ^5.0.0
